version: '2'
services:
    jhipster2-app:
        image: jhipster2
        external_links:
            - jhipster2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster2-mysql:
        extends:
            file: mysql.yml
            service: jhipster2-mysql
